/* Build step for the renderer:
 *   1. Pre-transform JSX -> plain JS (Electron loads it over file:// without
 *      runtime Babel, which can't fetch local files under CORS).
 *   2. Vendor the icon font (Phosphor) and web fonts (Fontsource) into the build
 *      output so the packaged app is fully offline — no CDN dependency.
 * Run with: node build.js  (also chained before `npm run dist`). */

"use strict";

const fs = require("fs");
const path = require("path");

let Babel = require("./renderer/vendor/babel.min.js");
if (!Babel || !Babel.transform) Babel = global.Babel;
if (!Babel || !Babel.transform) { console.error("Babel not available"); process.exit(1); }

const RENDERER = path.join(__dirname, "renderer");
const OUT = path.join(RENDERER, "build");
const NM = path.join(__dirname, "node_modules");
fs.mkdirSync(OUT, { recursive: true });

// Order matters: globals must be registered before App uses them.
const JSX = ["ui", "ActionBuilder", "KeyEditor", "Dashboard", "AutoSwitcher", "Settings", "CommandPalette", "App"];

// Plain JS, copied verbatim.
fs.copyFileSync(path.join(RENDERER, "data.js"), path.join(OUT, "data.js"));
fs.copyFileSync(path.join(RENDERER, "ledsim.js"), path.join(OUT, "ledsim.js"));

for (const name of JSX) {
  const src = fs.readFileSync(path.join(RENDERER, name + ".jsx"), "utf8");
  const { code } = Babel.transform(src, { presets: [["react"]], filename: name + ".jsx" });
  fs.writeFileSync(path.join(OUT, name + ".js"), code);
  console.log("built", name + ".js");
}

// ---- vendor assets (offline) ----------------------------------------------
function copyDir(from, to) {
  fs.mkdirSync(to, { recursive: true });
  for (const e of fs.readdirSync(from, { withFileTypes: true })) {
    const s = path.join(from, e.name), d = path.join(to, e.name);
    if (e.isDirectory()) copyDir(s, d);
    else fs.copyFileSync(s, d);
  }
}

// Phosphor icon weights used by the UI (regular = `ph`, plus bold + fill).
const phSrc = path.join(NM, "@phosphor-icons", "web", "src");
if (fs.existsSync(phSrc)) {
  for (const w of ["regular", "bold", "fill"]) copyDir(path.join(phSrc, w), path.join(OUT, "phosphor", w));
  console.log("vendored phosphor (regular, bold, fill)");
} else {
  console.warn("WARN: @phosphor-icons/web not installed — icons will be missing");
}

// Web fonts via Fontsource: copy the needed weights + emit @font-face CSS.
const FONT_DIR = path.join(OUT, "fonts");
fs.mkdirSync(FONT_DIR, { recursive: true });
const FONTS = [
  { pkg: "space-grotesk", family: "Space Grotesk" },
  { pkg: "hanken-grotesk", family: "Hanken Grotesk" },
  { pkg: "jetbrains-mono", family: "JetBrains Mono" },
];
const WEIGHTS = [400, 500, 600, 700];
let faceCss = "/* Vendored web fonts (offline) — generated by build.js */\n";
let fontCount = 0;
for (const { pkg, family } of FONTS) {
  const filesDir = path.join(NM, "@fontsource", pkg, "files");
  if (!fs.existsSync(filesDir)) { console.warn(`WARN: @fontsource/${pkg} not installed`); continue; }
  for (const w of WEIGHTS) {
    const src = path.join(filesDir, `${pkg}-latin-${w}-normal.woff2`);
    if (!fs.existsSync(src)) continue;
    const out = `${pkg}-${w}.woff2`;
    fs.copyFileSync(src, path.join(FONT_DIR, out));
    faceCss += `@font-face{font-family:"${family}";font-style:normal;font-weight:${w};font-display:swap;src:url("fonts/${out}") format("woff2");}\n`;
    fontCount++;
  }
}
fs.writeFileSync(path.join(OUT, "fonts.css"), faceCss);
console.log(`vendored ${fontCount} font files`);

console.log("renderer build complete ->", path.relative(__dirname, OUT));
